# Generated by Django 5.2.6 on 2025-09-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('booking_cancellation', 'Booking Cancellation'), ('payment_confirmation', 'Payment Confirmation'), ('welcome_email', 'Welcome Email'), ('password_reset', 'Password Reset'), ('review_request', 'Review Request')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Use {{variable}} for dynamic content')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='BookingMVP', max_length=100)),
                ('site_tagline', models.CharField(default='Your Perfect Stay Awaits', max_length=200)),
                ('site_description', models.TextField(default='Book amazing hotels worldwide')),
                ('contact_email', models.EmailField(default='contact@bookingmvp.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('support_email', models.EmailField(default='support@bookingmvp.com', max_length=254)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('default_tax_rate', models.DecimalField(decimal_places=4, default=0.1, max_digits=5)),
                ('service_fee_percentage', models.DecimalField(decimal_places=4, default=0.05, max_digits=5)),
                ('enable_reviews', models.BooleanField(default=True)),
                ('enable_coupons', models.BooleanField(default=True)),
                ('enable_wishlists', models.BooleanField(default=True)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
